services:
  db:
    image: mariadb:12
    restart: always
    secrets:
      - mariadb_password
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb_password
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - mariadb-network

networks:
  mariadb-network:

volumes:
  mariadb-data:

secrets:
  mariadb_password:
    file: ./mariadb-password.txt
